### PR TITLE
Us23 edit profile

### PR DESCRIPTION
**Pull request by Pyriac**

### CODE REVIEW

**Comment by Adiallo99** [comment]
Top, nickel

**Review by Adiallo99 — APPROVED** [review]

**Review by samihringuet — APPROVED** [review]
Goat Job !

**Review by geoffpech — APPROVED** [review]
GG !!! 🚀🚀🚀🚀🔥🔥🔥🔥

**Review by kpeset — APPROVED** [review]

**Review by kpeset — CHANGES_REQUESTED** [review]
COnflits :)

**Review by kpeset — APPROVED** [review]

**Pull request merged**
